version: "3.9"
services:
  web:
    container_name: web_app
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
      FLASK_APP: main.py
      FLASK_RUN_PORT: 8000

